In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv('bank.csv')

In [3]:
dataset.head()

age         job  marital  education default  balance housing loan  contact  \
0   59      admin.  married  secondary      no     2343     yes   no  unknown   
1   56      admin.  married  secondary      no       45      no   no  unknown   
2   41  technician  married  secondary      no     1270     yes   no  unknown   
3   55    services  married  secondary      no     2476     yes   no  unknown   
4   54      admin.  married   tertiary      no      184      no   no  unknown   

   day month  duration  campaign  pdays  previous poutcome deposit  
0    5   may      1042         1     -1         0  unknown     yes  
1    5   may      1467         1     -1         0  unknown     yes  
2    5   may      1389         1     -1         0  unknown     yes  
3    5   may       579         1     -1         0  unknown     yes  
4    5   may       673         2     -1         0  unknown     yes

In [4]:
dataset.isnull().any()

age          False
job          False
marital      False
education    False
default      False
balance      False
housing      False
loan         False
contact      False
day          False
month        False
duration     False
campaign     False
pdays        False
previous     False
poutcome     False
deposit      False
dtype: bool

In [5]:
dataset.head(1)

age     job  marital  education default  balance housing loan  contact  \
0   59  admin.  married  secondary      no     2343     yes   no  unknown   

   day month  duration  campaign  pdays  previous poutcome deposit  
0    5   may      1042         1     -1         0  unknown     yes

In [6]:
dataset['marital'].unique()

array(['married', 'single', 'divorced'], dtype=object)

In [7]:
dataset['education'].unique()

array(['secondary', 'tertiary', 'primary', 'unknown'], dtype=object)

In [8]:
dataset['job'].unique()

array(['admin.', 'technician', 'services', 'management', 'retired',
       'blue-collar', 'unemployed', 'entrepreneur', 'housemaid',
       'unknown', 'self-employed', 'student'], dtype=object)

In [9]:
dataset['default'].unique()

array(['no', 'yes'], dtype=object)

In [10]:
dataset['housing'].unique()

array(['yes', 'no'], dtype=object)

In [11]:
dataset['loan'].unique()

array(['no', 'yes'], dtype=object)

In [12]:
dataset['contact'].unique()

array(['unknown', 'cellular', 'telephone'], dtype=object)

In [13]:
dataset['month'].unique()

array(['may', 'jun', 'jul', 'aug', 'oct', 'nov', 'dec', 'jan', 'feb',
       'mar', 'apr', 'sep'], dtype=object)

In [14]:
dataset['poutcome'].unique()

array(['unknown', 'other', 'failure', 'success'], dtype=object)

In [8]:
dataset['job'].unique()

array(['admin.', 'technician', 'services', 'management', 'retired',
       'blue-collar', 'unemployed', 'entrepreneur', 'housemaid',
       'unknown', 'self-employed', 'student'], dtype=object)

In [15]:
dataset['deposit'].unique()

array(['yes', 'no'], dtype=object)

In [16]:
dataset.head(1)

age     job  marital  education default  balance housing loan  contact  \
0   59  admin.  married  secondary      no     2343     yes   no  unknown   

   day month  duration  campaign  pdays  previous poutcome deposit  
0    5   may      1042         1     -1         0  unknown     yes

In [17]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [19]:
dataset['job'] = le.fit_transform(dataset['job'])

In [20]:
dataset['marital'] = le.fit_transform(dataset['marital'])

In [21]:
dataset['education'] = le.fit_transform(dataset['education'])

In [22]:
dataset['default'] = le.fit_transform(dataset['default'])

In [23]:
dataset['housing'] = le.fit_transform(dataset['housing'])

In [24]:
dataset['loan'] = le.fit_transform(dataset['loan'])

In [25]:
dataset['contact'] = le.fit_transform(dataset['contact'])

In [26]:
dataset['month'] = le.fit_transform(dataset['month'])

In [27]:
dataset['poutcome'] = le.fit_transform(dataset['poutcome'])

In [28]:
dataset['deposit'] = le.fit_transform(dataset['deposit'])

In [30]:
dataset.head(10)

age  job  marital  education  default  balance  housing  loan  contact  \
0   59    0        1          1        0     2343        1     0        2   
1   56    0        1          1        0       45        0     0        2   
2   41    9        1          1        0     1270        1     0        2   
3   55    7        1          1        0     2476        1     0        2   
4   54    0        1          2        0      184        0     0        2   
5   42    4        2          2        0        0        1     1        2   
6   56    4        1          2        0      830        1     1        2   
7   60    5        0          1        0      545        1     0        2   
8   37    9        1          1        0        1        1     0        2   
9   28    7        2          1        0     5090        1     0        2   

   day  month  duration  campaign  pdays  previous  poutcome  deposit  
0    5      8      1042         1     -1         0         3        1  
1    5      8      1467         1     -1         0         3        1  
2    5      8      1389         1     -1         0         3        1  
3    5      8       579         1     -1         0         3        1  
4    5      8       673         2     -1         0         3        1  
5    5      8       562         2     -1         0         3        1  
6    6      8      1201         1     -1         0         3        1  
7    6      8      1030         1     -1         0         3        1  
8    6      8       608         1     -1         0         3        1  
9    6      8      1297         3     -1         0         3        1

In [31]:
dataset.shape

(11162, 17)

In [45]:
x = dataset.iloc[:,0:16].values
y = dataset.iloc[:,16].values

In [46]:
y

array([1, 1, 1, ..., 0, 0, 0])

In [47]:
x.shape

(11162, 16)

In [49]:
y.shape

(11162,)

In [50]:
x

array([[ 59,   0,   1, ...,  -1,   0,   3],
       [ 56,   0,   1, ...,  -1,   0,   3],
       [ 41,   9,   1, ...,  -1,   0,   3],
       ...,
       [ 32,   9,   2, ...,  -1,   0,   3],
       [ 43,   9,   1, ..., 172,   5,   0],
       [ 34,   9,   1, ...,  -1,   0,   3]], dtype=int64)

In [51]:
y

array([1, 1, 1, ..., 0, 0, 0])

In [155]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1000)

In [156]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [157]:
x_train

array([[-1.02610217, -1.08134411,  1.27749418, ..., -0.48145496,
        -0.36215413,  0.52073879],
       [-0.10016478,  1.39644419,  1.27749418, ..., -0.48145496,
        -0.36215413,  0.52073879],
       [-0.94192604, -1.08134411,  1.27749418, ..., -0.48145496,
        -0.36215413,  0.52073879],
       ...,
       [-0.35269316,  1.70616772, -0.32120877, ..., -0.48145496,
        -0.36215413,  0.52073879],
       [ 1.33082936, -1.39106765, -0.32120877, ...,  2.68603193,
         0.49832331, -1.47183746],
       [ 0.4890681 ,  0.77699711, -0.32120877, ..., -0.48145496,
        -0.36215413,  0.52073879]])

In [158]:
y_test

array([1, 1, 0, ..., 0, 0, 1])

In [159]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
logreg.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [160]:
ypred = logreg.predict(x_test)

In [161]:
ypred

array([1, 1, 0, ..., 0, 0, 1])

In [162]:
y_test

array([1, 1, 0, ..., 0, 0, 1])

In [163]:
from  sklearn.metrics import accuracy_score
accuracy = accuracy_score(ypred,y_test)

In [164]:
accuracy

0.8056426332288401

In [165]:
dataset.head(1)

age  job  marital  education  default  balance  housing  loan  contact  \
0   59    0        1          1        0     2343        1     0        2   

   day  month  duration  campaign  pdays  previous  poutcome  deposit  
0    5      8      1042         1     -1         0         3        1

In [166]:
dataset['month'].unique()

array([ 8,  6,  5,  1, 10,  9,  2,  4,  3,  7,  0, 11])

In [167]:
dataset['job'].unique()

array([ 0,  9,  7,  4,  5,  1, 10,  2,  3, 11,  6,  8])

In [168]:
logreg.predict(sc.transform([[29,5,1,1,0,457830,1,0,3,3,10,204,1,-1,0,2]]))

array([1])

In [169]:
logreg.predict(sc.transform([[39,0,0,0,0,57830,1,0,4,3,10,1004,1,-1,1,2]]))

array([1])