In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv('Fish.csv')

In [3]:
dataset.head()

Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

In [4]:
dataset.isnull().any()

Species    False
Weight     False
Length1    False
Length2    False
Length3    False
Height     False
Width      False
dtype: bool

In [6]:
dataset['Species'].unique()

array(['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt'],
      dtype=object)

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [8]:
dataset['Species']=le.fit_transform(dataset['Species'])

In [9]:
dataset.head()

Species  Weight  Length1  Length2  Length3   Height   Width
0        0   242.0     23.2     25.4     30.0  11.5200  4.0200
1        0   290.0     24.0     26.3     31.2  12.4800  4.3056
2        0   340.0     23.9     26.5     31.1  12.3778  4.6961
3        0   363.0     26.3     29.0     33.5  12.7300  4.4555
4        0   430.0     26.5     29.0     34.0  12.4440  5.1340

In [10]:
dataset.shape

(159, 7)

In [15]:
x = dataset.iloc[:,[0,2,3,4,5,6]]
y = dataset.iloc[:,1]

In [16]:
x

Species  Length1  Length2  Length3   Height   Width
0          0     23.2     25.4     30.0  11.5200  4.0200
1          0     24.0     26.3     31.2  12.4800  4.3056
2          0     23.9     26.5     31.1  12.3778  4.6961
3          0     26.3     29.0     33.5  12.7300  4.4555
4          0     26.5     29.0     34.0  12.4440  5.1340
..       ...      ...      ...      ...      ...     ...
154        5     11.5     12.2     13.4   2.0904  1.3936
155        5     11.7     12.4     13.5   2.4300  1.2690
156        5     12.1     13.0     13.8   2.2770  1.2558
157        5     13.2     14.3     15.2   2.8728  2.0672
158        5     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 6 columns]

In [17]:
y

0      242.0
1      290.0
2      340.0
3      363.0
4      430.0
       ...  
154     12.2
155     13.4
156     12.2
157     19.7
158     19.9
Name: Weight, Length: 159, dtype: float64

In [38]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state = 80)

In [39]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [40]:
lr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [41]:
ypred = lr.predict(x_test)

In [42]:
ypred

array([ 129.7912298 ,  139.62689608,  562.05331326,  904.633789  ,
        147.40809828,  452.78746361,  498.35671646,  335.28960668,
        656.26451152,   97.151702  ,  180.80099895,  731.88422213,
        255.26211908,  847.8165702 ,  143.80887163,  645.13779319,
        391.03526001,  990.32433999,  826.42471694,  678.93584907,
        843.01482625,  299.28643608,  198.35845887,  111.6265588 ,
        408.66959555,  561.57003853, -138.12667703,  429.02694636,
        405.86827155, -317.51400888,  631.20413037,  719.49224314])

In [43]:
y_test

90      110.0
94      150.0
57      306.0
124    1000.0
65      150.0
5       450.0
55      270.0
2       340.0
21      685.0
36       69.0
42      120.0
28      850.0
45      160.0
29     1000.0
89      135.0
23      680.0
128     200.0
60     1000.0
118     820.0
135     510.0
30      920.0
48      169.0
95      170.0
82      110.0
52      290.0
14      600.0
149       9.8
130     300.0
53      272.0
72        5.9
18      610.0
58      540.0
Name: Weight, dtype: float64

In [44]:
dataset.head()

Species  Weight  Length1  Length2  Length3   Height   Width
0        0   242.0     23.2     25.4     30.0  11.5200  4.0200
1        0   290.0     24.0     26.3     31.2  12.4800  4.3056
2        0   340.0     23.9     26.5     31.1  12.3778  4.6961
3        0   363.0     26.3     29.0     33.5  12.7300  4.4555
4        0   430.0     26.5     29.0     34.0  12.4440  5.1340

In [45]:
dataset['Species'].unique()

array([0, 4, 6, 1, 2, 3, 5])

In [48]:
from sklearn.metrics import r2_score
accuracy = r2_score(ypred,y_test)

In [49]:
accuracy

0.8437567578841461

In [55]:
yp = lr.predict([[1,25.3,29.9,34.0,10.2343,5.4022]])

In [56]:
yp

array([390.18298929])

In [58]:
yp = lr.predict([[3,25.3,23.9,24.0,14.2343,5.4022]])

In [59]:
yp

array([661.30298405])